spring:
  datasource:
    url: jdbc-secretsmanager:postgresql://theater-db-dev.c0gmxvr41yrz.ap-southeast-2.rds.amazonaws.com:5432/theater
    driverClassName: com.amazonaws.secretsmanager.sql.AWSSecretsManagerPostgreSQLDriver
    username: rds!db-8794b5e6-6537-448e-b263-d3840d21d0e4
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
cloud.aws:
  region: ap-southeast-2
  reportSQSUrl:
    premium: theater-report-premium-bookings-dev
    all: theater-report-all-bookings-dev

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc-secretsmanager:postgresql://theater-db-dev.c0gmxvr41yrz.ap-southeast-2.rds.amazonaws.com:5432/theater
    driverClassName: com.amazonaws.secretsmanager.sql.AWSSecretsManagerPostgreSQLDriver
    username: rds!db-8794b5e6-6537-448e-b263-d3840d21d0e4
cloud.aws:
  reportSQSUrl:
    premium: theater-report-premium-bookings-dev
    all: theater-report-all-bookings-dev

---
spring:
  config:
    activate:
      on-profile: staging
  datasource:
    url: jdbc-secretsmanager:postgresql://theater-db-dev.c0gmxvr41yrz.ap-southeast-2.rds.amazonaws.com:5432/theater
    driverClassName: com.amazonaws.secretsmanager.sql.AWSSecretsManagerPostgreSQLDriver
    username: rds!db-8794b5e6-6537-448e-b263-d3840d21d0e4
cloud.aws:
  reportSQSUrl:
    premium: theater-report-premium-bookings-stg
    all: theater-report-all-bookings-stg

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc-secretsmanager:postgresql://theater-db-dev.c0gmxvr41yrz.ap-southeast-2.rds.amazonaws.com:5432/theater
    driverClassName: com.amazonaws.secretsmanager.sql.AWSSecretsManagerPostgreSQLDriver
    username: rds!db-8794b5e6-6537-448e-b263-d3840d21d0e4
cloud.aws:
  reportSQSUrl:
    premium: theater-report-premium-bookings-prod
    all: theater-report-all-bookings-prod