spring:
  datasource:
    url: jdbc:h2:file:~/theater;AUTO_SERVER=TRUE
    driverClassName: org.h2.Driver
    username: sa
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
